-- =============================================
-- DentalShift PRO: 正規化データベースマイグレーション
-- Supabase SQL Editor で実行してください
-- =============================================

-- 1. スタッフ
CREATE TABLE IF NOT EXISTS staff (
  id             int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name           text NOT NULL,
  role           text NOT NULL CHECK (role IN ('Dr','Dh','Da','受付','技工士','TC')),
  leave_days     int NOT NULL DEFAULT 10,
  used_days      int NOT NULL DEFAULT 0,
  active         boolean NOT NULL DEFAULT true,
  kyosei_order   int,
  birth_date     text NOT NULL DEFAULT '',
  join_year      int,
  employment     text NOT NULL DEFAULT '正社員' CHECK (employment IN ('正社員','パート')),
  weekly_days_off numeric(2,1),
  login_id       text UNIQUE,
  pin            text,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);

-- 2. スタッフ定休日
CREATE TABLE IF NOT EXISTS staff_rest_days (
  id        int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  staff_id  int NOT NULL REFERENCES staff(id) ON DELETE CASCADE,
  dow       int NOT NULL CHECK (dow BETWEEN 0 AND 6),
  type      text NOT NULL CHECK (type IN ('全休','午前休','午後休')),
  UNIQUE (staff_id, dow)
);

-- 3. シフト
CREATE TABLE IF NOT EXISTS shifts (
  id         bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  staff_id   int NOT NULL REFERENCES staff(id) ON DELETE CASCADE,
  year       int NOT NULL,
  month      int NOT NULL CHECK (month BETWEEN 0 AND 11),
  day        int NOT NULL CHECK (day BETWEEN 1 AND 31),
  shift_type text NOT NULL,
  is_preview boolean NOT NULL DEFAULT false,
  UNIQUE (staff_id, year, month, day, is_preview)
);
CREATE INDEX IF NOT EXISTS idx_shifts_month ON shifts (year, month);
CREATE INDEX IF NOT EXISTS idx_shifts_staff ON shifts (staff_id, year, month);

-- 4. 希望シフト
CREATE TABLE IF NOT EXISTS wishes (
  id         bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  staff_id   int NOT NULL REFERENCES staff(id) ON DELETE CASCADE,
  year       int NOT NULL,
  month      int NOT NULL CHECK (month BETWEEN 0 AND 11),
  day        int NOT NULL CHECK (day BETWEEN 1 AND 31),
  shift_type text NOT NULL,
  UNIQUE (staff_id, year, month, day)
);

-- 5. 医院休診日
CREATE TABLE IF NOT EXISTS clinic_holidays (
  id     int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  date   date NOT NULL UNIQUE,
  label  text NOT NULL DEFAULT ''
);

-- 6. 矯正日オーバーライド（追加・削除）
CREATE TABLE IF NOT EXISTS kyosei_overrides (
  id      int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  year    int NOT NULL,
  month   int NOT NULL CHECK (month BETWEEN 0 AND 11),
  day     int NOT NULL CHECK (day BETWEEN 1 AND 31),
  action  text NOT NULL CHECK (action IN ('add', 'delete')),
  type    text CHECK (type IN ('土','木')),
  label   text,
  UNIQUE (year, month, day),
  CHECK (action = 'delete' OR type IS NOT NULL)
);

-- 7. セミナー
CREATE TABLE IF NOT EXISTS seminars (
  id         int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name       text NOT NULL,
  date       date NOT NULL,
  start_time text NOT NULL,
  end_time   text NOT NULL,
  break_min  int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS seminar_staff (
  seminar_id int NOT NULL REFERENCES seminars(id) ON DELETE CASCADE,
  staff_id   int NOT NULL REFERENCES staff(id) ON DELETE CASCADE,
  PRIMARY KEY (seminar_id, staff_id)
);

-- 8. 訪問
CREATE TABLE IF NOT EXISTS visits (
  id         int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name       text NOT NULL DEFAULT '訪問',
  date       date NOT NULL,
  start_time text NOT NULL,
  end_time   text NOT NULL,
  break_min  int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS visit_staff (
  visit_id int NOT NULL REFERENCES visits(id) ON DELETE CASCADE,
  staff_id int NOT NULL REFERENCES staff(id) ON DELETE CASCADE,
  PRIMARY KEY (visit_id, staff_id)
);

-- 9. 設定（シングルトン）
CREATE TABLE IF NOT EXISTS clinic_settings (
  id text PRIMARY KEY DEFAULT 'default',
  min_staff       jsonb NOT NULL DEFAULT '{"Dr":1,"Dh":2,"Da":1,"受付":1}',
  wh_start        text NOT NULL DEFAULT '08:45',
  wh_end          text NOT NULL DEFAULT '18:30',
  wh_break_min    int NOT NULL DEFAULT 90,
  wh_sat_start    text NOT NULL DEFAULT '08:45',
  wh_sat_end      text NOT NULL DEFAULT '15:30',
  wh_sat_break_min int NOT NULL DEFAULT 30,
  kyosei_sat_start text NOT NULL DEFAULT '14:00',
  kyosei_sat_end   text NOT NULL DEFAULT '17:30',
  kyosei_thu_start text NOT NULL DEFAULT '14:00',
  kyosei_thu_end   text NOT NULL DEFAULT '18:30',
  cal_start        int NOT NULL DEFAULT 11 CHECK (cal_start IN (1, 11)),
  updated_at       timestamptz NOT NULL DEFAULT now()
);

-- デフォルト設定行を挿入
INSERT INTO clinic_settings (id) VALUES ('default') ON CONFLICT DO NOTHING;

-- =============================================
-- RLS (Row Level Security)
-- =============================================
ALTER TABLE staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff_rest_days ENABLE ROW LEVEL SECURITY;
ALTER TABLE shifts ENABLE ROW LEVEL SECURITY;
ALTER TABLE wishes ENABLE ROW LEVEL SECURITY;
ALTER TABLE clinic_holidays ENABLE ROW LEVEL SECURITY;
ALTER TABLE kyosei_overrides ENABLE ROW LEVEL SECURITY;
ALTER TABLE seminars ENABLE ROW LEVEL SECURITY;
ALTER TABLE seminar_staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE visits ENABLE ROW LEVEL SECURITY;
ALTER TABLE visit_staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE clinic_settings ENABLE ROW LEVEL SECURITY;

-- anon ユーザーに全テーブルの読み書きを許可（認証導入後に制限する）
CREATE POLICY "allow_all_staff" ON staff FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all_staff_rest_days" ON staff_rest_days FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all_shifts" ON shifts FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all_wishes" ON wishes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all_clinic_holidays" ON clinic_holidays FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all_kyosei_overrides" ON kyosei_overrides FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all_seminars" ON seminars FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all_seminar_staff" ON seminar_staff FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all_visits" ON visits FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all_visit_staff" ON visit_staff FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "allow_all_clinic_settings" ON clinic_settings FOR ALL USING (true) WITH CHECK (true);
